global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using System.Text;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Practical17.Domain.Common.AuditingConracts;
global using Microsoft.Extensions.Configuration;
global using Practical17.Domain.Entities;
global using Practical17.Infrastructure.Data.DbContext;
global using Practical17.Infrastructure.Data.Interceptors;
global using ApplicationRole = Practical17.Infrastructure.Identity.ApplicationRole;
global using ApplicationUser = Practical17.Infrastructure.Identity.ApplicationUser;
global using Practical17.Infrastructure.Repositories.Contracts;
global using Practical17.Infrastructure.Repositories.Implementations;
global using Practical17.Infrastructure.UnitOfWorkPattern;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
